
package pigcontrol;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VacunasDesparasitantes extends javax.swing.JFrame {
 DefaultTableModel dtm;
    Object[] o = new Object[5];
    int filaSeleccionada;
    public void limpiar(){
       IdPorcino.setText(""); 
       Vacuna.setText("");
       Desparasitante.setText("");
       UltVacuna.setText("");
       UltDesparasitante.setText("");
    }
    public VacunasDesparasitantes() {
        initComponents();
        dtm = (DefaultTableModel) tUsuarios.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        IdPorcino = new javax.swing.JTextField();
        Vacuna = new javax.swing.JTextField();
        Desparasitante = new javax.swing.JTextField();
        UltVacuna = new javax.swing.JTextField();
        UltDesparasitante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tUsuarios = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vacunas y Desparasitantes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 712, -1));

        jLabel2.setText("IdPorcino");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, -1, -1));

        jLabel3.setText("Vacuna");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 101, -1, -1));

        jLabel4.setText("Desparasitante");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));

        jLabel5.setText("Ultima Vacuna");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel6.setText("Ultimo Desparasitante");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 498, 100, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 202, 85, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Eliminar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 158, 85, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 109, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 58, -1, -1));
        getContentPane().add(IdPorcino, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 51, 99, -1));
        getContentPane().add(Vacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 89, 99, -1));

        Desparasitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesparasitanteActionPerformed(evt);
            }
        });
        getContentPane().add(Desparasitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 132, 99, -1));
        getContentPane().add(UltVacuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 170, 99, -1));

        UltDesparasitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UltDesparasitanteActionPerformed(evt);
            }
        });
        getContentPane().add(UltDesparasitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 208, 99, -1));

        tUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdPorcino", "Vacunas", "Desparasitantes", "UltDesparasitante", "UltVacuna"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tUsuarios);
        if (tUsuarios.getColumnModel().getColumnCount() > 0) {
            tUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tUsuarios.getColumnModel().getColumn(1).setResizable(false);
            tUsuarios.getColumnModel().getColumn(2).setResizable(false);
            tUsuarios.getColumnModel().getColumn(3).setResizable(false);
            tUsuarios.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 246, 712, 218));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Menu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/Fondo_Amplio.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        filaSeleccionada = tUsuarios.getSelectedRow();
        if (filaSeleccionada !=-1) {
            limpiar();

            IdPorcino.setText( tUsuarios.getValueAt(filaSeleccionada,0).toString());
            Vacuna.setText( tUsuarios.getValueAt(filaSeleccionada,1).toString());
            Desparasitante.setText( tUsuarios.getValueAt(filaSeleccionada,2).toString());
            UltVacuna.setText( tUsuarios.getValueAt(filaSeleccionada, 3).toString());
            UltDesparasitante.setText( tUsuarios.getValueAt(filaSeleccionada,4).toString());
            System.out.println("Fila seleccionada :  "+ filaSeleccionada);
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione una Casilla ...","Titulo",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if ((((!IdPorcino.getText().equals("") && !Vacuna.getText().equals("")) && !Desparasitante.getText().equals("")) && !UltVacuna.getText().equals(""))&& !UltDesparasitante.getText().equals("")) {
            o[0] = IdPorcino.getText();
            o[1] = Vacuna.getText();
            o[2] = Desparasitante.getText();
            o[3] = UltVacuna.getText();
            o[4] = UltDesparasitante.getText();
            dtm.addRow(o);

            for (int i = 0; i < o.length; i++) {
                o[i] = "";
            }
            limpiar();
        }else{
            JOptionPane.showMessageDialog(null, "No se Ingresado Ningun valor ...","Titulo",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void DesparasitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesparasitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DesparasitanteActionPerformed

    private void UltDesparasitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UltDesparasitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UltDesparasitanteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VacunasDesparasitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VacunasDesparasitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VacunasDesparasitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VacunasDesparasitantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VacunasDesparasitantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Desparasitante;
    private javax.swing.JTextField IdPorcino;
    private javax.swing.JTextField UltDesparasitante;
    private javax.swing.JTextField UltVacuna;
    private javax.swing.JTextField Vacuna;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tUsuarios;
    // End of variables declaration//GEN-END:variables
}
